CRITICAL - 2025-05-24 03:17:32 --> ErrorException: Undefined variable $gradeLevels
[Method: GET, Route: profile]
in APPPATH\Views\profile.php on line 64.
 1 APPPATH\Views\profile.php(64): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $gradeLevels', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\profile.php', 64)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\profile.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('profile', [], true)
 5 APPPATH\Controllers\Home.php(219): view('profile')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->profile()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 03:48:43 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: updateMember/js/scripts.js]
in APPPATH\Views\updateMember.php on line 37.
 1 APPPATH\Views\updateMember.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('updateMember', [], true)
 5 APPPATH\Controllers\Member.php(133): view('updateMember', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Member->updateMember('js', 'scripts.js')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Member))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 03:48:43 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: updateMember/assets/demo/chart-area-demo.js]
in APPPATH\Views\updateMember.php on line 37.
 1 APPPATH\Views\updateMember.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('updateMember', [], true)
 5 APPPATH\Controllers\Member.php(133): view('updateMember', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Member->updateMember('assets', 'demo', 'chart-area-demo.js')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Member))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 03:48:43 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: updateMember/assets/demo/chart-bar-demo.js]
in APPPATH\Views\updateMember.php on line 37.
 1 APPPATH\Views\updateMember.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('updateMember', [], true)
 5 APPPATH\Controllers\Member.php(133): view('updateMember', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Member->updateMember('assets', 'demo', 'chart-bar-demo.js')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Member))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 03:48:43 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: updateMember/js/datatables-simple-demo.js]
in APPPATH\Views\updateMember.php on line 37.
 1 APPPATH\Views\updateMember.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('updateMember', [], true)
 5 APPPATH\Controllers\Member.php(133): view('updateMember', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Member->updateMember('js', 'datatables-simple-demo.js')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Member))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:07:28 --> ErrorException: Undefined variable $conn
[Method: GET, Route: profile]
in APPPATH\Views\profile.php on line 74.
 1 APPPATH\Views\profile.php(74): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $conn', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\profile.php', 74)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\profile.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('profile', [], true)
 5 APPPATH\Controllers\Home.php(219): view('profile')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->profile()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:17:40 --> CodeIgniter\View\Exceptions\ViewException: Invalid file: "profile.php"
[Method: GET, Route: profile]
in SYSTEMPATH\Exceptions\FrameworkException.php on line 39.
 1 SYSTEMPATH\View\View.php(212): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('profile.php')
 2 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('profile', [], true)
 3 APPPATH\Controllers\Home.php(219): view('profile')
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->profile()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-24 05:41:04 --> mysqli_sql_exception: Unknown column 'title' in 'field list' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `an...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `an...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `an...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `an...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\xampp\htdocs\Psits_System\app\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert(Array)
#8 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement(Array)
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-05-24 05:41:04 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'title' in 'field list'
[Method: POST, Route: add_announcement]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:41:04 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'title' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:41:04\', \'2025-05-24 05:41:04\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:41:04\', \'2025-05-24 05:41:04\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:41:04 --> [Caused by] mysqli_sql_exception: Unknown column 'title' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:41:04\', \'2025-05-24 05:41:04\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:41:04\', \'2025-05-24 05:41:04\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:41:04\', \'2025-05-24 05:41:04\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-24 05:42:29 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `an...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `an...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `an...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `an...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\xampp\htdocs\Psits_System\app\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert(Array)
#8 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement(Array)
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-05-24 05:42:29 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: add_announcement]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:42:29 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:42:29\', \'2025-05-24 05:42:29\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:42:29\', \'2025-05-24 05:42:29\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:42:29 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:42:29\', \'2025-05-24 05:42:29\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:42:29\', \'2025-05-24 05:42:29\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:42:29\', \'2025-05-24 05:42:29\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-24 05:42:30 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `an...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `an...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `an...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `an...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\xampp\htdocs\Psits_System\app\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert(Array)
#8 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement(Array)
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-05-24 05:42:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: add_announcement]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:42:30 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:42:30\', \'2025-05-24 05:42:30\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:42:30\', \'2025-05-24 05:42:30\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:42:30 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:42:30\', \'2025-05-24 05:42:30\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:42:30\', \'2025-05-24 05:42:30\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:42:30\', \'2025-05-24 05:42:30\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-24 05:47:50 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `an...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `an...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `an...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `an...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\xampp\htdocs\Psits_System\app\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert(Array)
#8 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement(Array)
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-05-24 05:47:50 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: add_announcement]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:47:50 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:47:50\', \'2025-05-24 05:47:50\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:47:50\', \'2025-05-24 05:47:50\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:47:50 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:47:50\', \'2025-05-24 05:47:50\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:47:50\', \'2025-05-24 05:47:50\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:47:50\', \'2025-05-24 05:47:50\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-24 05:47:51 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `an...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `an...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `an...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `an...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\xampp\htdocs\Psits_System\app\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert(Array)
#8 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement(Array)
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-05-24 05:47:51 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: add_announcement]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:47:51 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:47:51\', \'2025-05-24 05:47:51\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:47:51\', \'2025-05-24 05:47:51\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:47:51 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:47:51\', \'2025-05-24 05:47:51\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:47:51\', \'2025-05-24 05:47:51\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:47:51\', \'2025-05-24 05:47:51\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-24 05:48:10 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `an...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `an...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `an...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `an...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\xampp\htdocs\Psits_System\app\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert(Array)
#8 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement(Array)
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-05-24 05:48:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: add_announcement]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:48:10 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:48:10\', \'2025-05-24 05:48:10\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:48:10\', \'2025-05-24 05:48:10\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:48:10 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:48:10\', \'2025-05-24 05:48:10\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:48:10\', \'2025-05-24 05:48:10\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:48:10\', \'2025-05-24 05:48:10\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-24 05:48:51 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `an...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `an...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `an...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `an...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\xampp\htdocs\Psits_System\app\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert(Array)
#8 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement(Array)
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-05-24 05:48:51 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: add_announcement]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:48:51 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:48:51\', \'2025-05-24 05:48:51\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:48:51\', \'2025-05-24 05:48:51\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:48:51 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:48:51\', \'2025-05-24 05:48:51\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:48:51\', \'2025-05-24 05:48:51\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:48:51\', \'2025-05-24 05:48:51\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-24 05:50:04 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `an...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `an...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `an...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `an...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\xampp\htdocs\Psits_System\app\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert(Array)
#8 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement(Array)
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-05-24 05:50:04 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: add_announcement]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:50:04 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:50:04\', \'2025-05-24 05:50:04\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:50:04\', \'2025-05-24 05:50:04\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:50:04 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:50:04\', \'2025-05-24 05:50:04\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:50:04\', \'2025-05-24 05:50:04\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:50:04\', \'2025-05-24 05:50:04\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-24 05:50:23 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `an...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `an...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `an...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `an...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\xampp\htdocs\Psits_System\app\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert(Array)
#8 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement(Array)
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-05-24 05:50:23 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: add_announcement]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:50:23 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:50:23\', \'2025-05-24 05:50:23\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:50:23\', \'2025-05-24 05:50:23\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:50:23 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:50:23\', \'2025-05-24 05:50:23\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:50:23\', \'2025-05-24 05:50:23\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:50:23\', \'2025-05-24 05:50:23\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-24 05:50:37 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `an...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `an...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `an...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `an...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\xampp\htdocs\Psits_System\app\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert(Array)
#8 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement(Array)
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-05-24 05:50:37 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: add_announcement]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:50:37 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:50:37\', \'2025-05-24 05:50:37\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:50:37\', \'2025-05-24 05:50:37\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:50:37 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:50:37\', \'2025-05-24 05:50:37\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:50:37\', \'2025-05-24 05:50:37\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:50:37\', \'2025-05-24 05:50:37\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-24 05:50:38 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `an...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `an...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `an...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `an...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\xampp\htdocs\Psits_System\app\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert(Array)
#8 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement(Array)
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-05-24 05:50:38 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: add_announcement]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:50:38 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:50:38\', \'2025-05-24 05:50:38\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:50:38\', \'2025-05-24 05:50:38\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:50:38 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:50:38\', \'2025-05-24 05:50:38\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:50:38\', \'2025-05-24 05:50:38\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:50:38\', \'2025-05-24 05:50:38\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-24 05:51:34 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `an...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `an...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `an...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `an...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\xampp\htdocs\Psits_System\app\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert(Array)
#8 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement(Array)
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-05-24 05:51:34 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: add_announcement]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:51:34 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:51:34\', \'2025-05-24 05:51:34\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:51:34\', \'2025-05-24 05:51:34\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:51:34 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:51:34\', \'2025-05-24 05:51:34\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:51:34\', \'2025-05-24 05:51:34\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:51:34\', \'2025-05-24 05:51:34\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-24 05:51:37 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `an...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `an...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `an...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `an...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\xampp\htdocs\Psits_System\app\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert(Array)
#8 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement(Array)
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-05-24 05:51:37 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: add_announcement]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:51:37 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:51:37\', \'2025-05-24 05:51:37\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:51:37\', \'2025-05-24 05:51:37\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:51:37 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:51:37\', \'2025-05-24 05:51:37\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:51:37\', \'2025-05-24 05:51:37\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:51:37\', \'2025-05-24 05:51:37\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-24 05:51:39 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `an...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `an...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `an...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `an...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\xampp\htdocs\Psits_System\app\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert(Array)
#8 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement(Array)
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-05-24 05:51:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: add_announcement]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:51:39 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:51:39\', \'2025-05-24 05:51:39\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:51:39\', \'2025-05-24 05:51:39\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:51:39 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:51:39\', \'2025-05-24 05:51:39\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:51:39\', \'2025-05-24 05:51:39\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:51:39\', \'2025-05-24 05:51:39\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-24 05:51:56 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `an...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `an...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `an...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `an...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\xampp\htdocs\Psits_System\app\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert(Array)
#8 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement(Array)
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-05-24 05:51:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: add_announcement]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:51:56 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:51:56\', \'2025-05-24 05:51:56\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:51:56\', \'2025-05-24 05:51:56\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:51:56 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:51:56\', \'2025-05-24 05:51:56\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:51:56\', \'2025-05-24 05:51:56\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:51:56\', \'2025-05-24 05:51:56\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-24 05:52:12 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `an...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `an...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `an...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `an...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\xampp\htdocs\Psits_System\app\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert(Array)
#8 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement(Array)
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-05-24 05:52:12 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: add_announcement]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:52:12 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:52:12\', \'2025-05-24 05:52:12\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:52:12\', \'2025-05-24 05:52:12\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:52:12 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:52:12\', \'2025-05-24 05:52:12\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:52:12\', \'2025-05-24 05:52:12\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:52:12\', \'2025-05-24 05:52:12\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-24 05:52:14 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 D:\xampp\htdocs\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `an...', 0)
#1 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `an...')
#2 D:\xampp\htdocs\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `an...')
#3 D:\xampp\htdocs\Psits_System\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `an...', Array, false)
#4 D:\xampp\htdocs\Psits_System\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\Psits_System\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\Psits_System\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 D:\xampp\htdocs\Psits_System\app\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert(Array)
#8 D:\xampp\htdocs\Psits_System\app\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement(Array)
#9 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
#10 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#11 D:\xampp\htdocs\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\Psits_System\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
CRITICAL - 2025-05-24 05:52:14 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: add_announcement]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 6 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:52:14 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:52:14\', \'2025-05-24 05:52:14\')')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:52:14\', \'2025-05-24 05:52:14\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 8 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:52:14 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:52:14\', \'2025-05-24 05:52:14\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:52:14\', \'2025-05-24 05:52:14\')')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (\'asda\', \'dada\', \'asda\', \'dasdada\', \'dasda\', \'dada\', \'pending\', \'2025-05-24 05:52:14\', \'2025-05-24 05:52:14\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `announcements` (`title`, `who`, `what`, `when`, `where`, `content`, `status`, `created_at`, `updated_at`) VALUES (:title:, :who:, :what:, :when:, :where:, :content:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(839): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(800): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Models\AnnouncementModel.php(22): CodeIgniter\Model->insert([...])
 9 APPPATH\Controllers\Home.php(240): App\Models\AnnouncementModel->addAnnouncement([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->addAnnouncement()
11 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
12 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:56:36 --> TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given
[Method: GET, Route: announcement]
in APPPATH\Views\announcement.php on line 93.
 1 SYSTEMPATH\View\View.php(224): include()
 2 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('announcement', [], true)
 4 APPPATH\Controllers\Home.php(223): view('announcement')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->announcement()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 05:56:36 --> [Caused by] ErrorException: Undefined variable $pendingAnnouncements
in APPPATH\Views\announcement.php on line 93.
 1 APPPATH\Views\announcement.php(93): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $pendingAnnouncements', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\announcement.php', 93)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\announcement.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('announcement', [], true)
 5 APPPATH\Controllers\Home.php(223): view('announcement')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->announcement()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 06:06:48 --> ErrorException: Undefined variable $announcementModel
[Method: GET, Route: announcement]
in APPPATH\Views\announcement.php on line 95.
 1 APPPATH\Views\announcement.php(95): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $announcementModel', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\announcement.php', 95)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\announcement.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('announcement', [], true)
 5 APPPATH\Controllers\Home.php(227): view('announcement', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->announcement()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 06:07:13 --> ErrorException: Undefined array key "date_submitted"
[Method: GET, Route: announcement]
in APPPATH\Views\announcement.php on line 99.
 1 APPPATH\Views\announcement.php(99): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "date_submitted"', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\announcement.php', 99)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\announcement.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('announcement', [], true)
 5 APPPATH\Controllers\Home.php(227): view('announcement', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->announcement()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 08:24:12 --> ErrorException: date_default_timezone_set(): Timezone ID 'PHT' is invalid
[Method: GET, Route: announcement]
in SYSTEMPATH\CodeIgniter.php on line 192.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(8, 'date_default_timezone_set(): Timezone ID \'PHT\' is invalid', 'D:\\xampp\\htdocs\\Psits_System\\system\\CodeIgniter.php', 192)
 2 SYSTEMPATH\CodeIgniter.php(192): date_default_timezone_set('PHT')
 3 SYSTEMPATH\Boot.php(321): CodeIgniter\CodeIgniter->initialize()
 4 SYSTEMPATH\Boot.php(66): CodeIgniter\Boot::initializeCodeIgniter()
 5 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 6 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 08:24:13 --> ErrorException: date_default_timezone_set(): Timezone ID 'PHT' is invalid
[Method: GET, Route: announcement]
in SYSTEMPATH\CodeIgniter.php on line 192.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(8, 'date_default_timezone_set(): Timezone ID \'PHT\' is invalid', 'D:\\xampp\\htdocs\\Psits_System\\system\\CodeIgniter.php', 192)
 2 SYSTEMPATH\CodeIgniter.php(192): date_default_timezone_set('PHT')
 3 SYSTEMPATH\Boot.php(321): CodeIgniter\CodeIgniter->initialize()
 4 SYSTEMPATH\Boot.php(66): CodeIgniter\Boot::initializeCodeIgniter()
 5 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 6 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 08:24:14 --> ErrorException: date_default_timezone_set(): Timezone ID 'PHT' is invalid
[Method: GET, Route: announcement]
in SYSTEMPATH\CodeIgniter.php on line 192.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(8, 'date_default_timezone_set(): Timezone ID \'PHT\' is invalid', 'D:\\xampp\\htdocs\\Psits_System\\system\\CodeIgniter.php', 192)
 2 SYSTEMPATH\CodeIgniter.php(192): date_default_timezone_set('PHT')
 3 SYSTEMPATH\Boot.php(321): CodeIgniter\CodeIgniter->initialize()
 4 SYSTEMPATH\Boot.php(66): CodeIgniter\Boot::initializeCodeIgniter()
 5 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 6 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 08:24:19 --> ErrorException: date_default_timezone_set(): Timezone ID 'UTH' is invalid
[Method: GET, Route: announcement]
in SYSTEMPATH\CodeIgniter.php on line 192.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(8, 'date_default_timezone_set(): Timezone ID \'UTH\' is invalid', 'D:\\xampp\\htdocs\\Psits_System\\system\\CodeIgniter.php', 192)
 2 SYSTEMPATH\CodeIgniter.php(192): date_default_timezone_set('UTH')
 3 SYSTEMPATH\Boot.php(321): CodeIgniter\CodeIgniter->initialize()
 4 SYSTEMPATH\Boot.php(66): CodeIgniter\Boot::initializeCodeIgniter()
 5 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 6 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 08:24:20 --> ErrorException: date_default_timezone_set(): Timezone ID 'UTH' is invalid
[Method: GET, Route: announcement]
in SYSTEMPATH\CodeIgniter.php on line 192.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(8, 'date_default_timezone_set(): Timezone ID \'UTH\' is invalid', 'D:\\xampp\\htdocs\\Psits_System\\system\\CodeIgniter.php', 192)
 2 SYSTEMPATH\CodeIgniter.php(192): date_default_timezone_set('UTH')
 3 SYSTEMPATH\Boot.php(321): CodeIgniter\CodeIgniter->initialize()
 4 SYSTEMPATH\Boot.php(66): CodeIgniter\Boot::initializeCodeIgniter()
 5 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 6 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 08:26:07 --> ErrorException: date_default_timezone_set(): Timezone ID 'GMT+8' is invalid
[Method: GET, Route: announcement]
in SYSTEMPATH\CodeIgniter.php on line 192.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(8, 'date_default_timezone_set(): Timezone ID \'GMT+8\' is invalid', 'D:\\xampp\\htdocs\\Psits_System\\system\\CodeIgniter.php', 192)
 2 SYSTEMPATH\CodeIgniter.php(192): date_default_timezone_set('GMT+8')
 3 SYSTEMPATH\Boot.php(321): CodeIgniter\CodeIgniter->initialize()
 4 SYSTEMPATH\Boot.php(66): CodeIgniter\Boot::initializeCodeIgniter()
 5 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 6 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 14:53:52 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: updateMember/js/scripts.js]
in APPPATH\Views\updateMember.php on line 37.
 1 APPPATH\Views\updateMember.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('updateMember', [], true)
 5 APPPATH\Controllers\Member.php(133): view('updateMember', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Member->updateMember('js', 'scripts.js')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Member))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 14:53:52 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: updateMember/assets/demo/chart-area-demo.js]
in APPPATH\Views\updateMember.php on line 37.
 1 APPPATH\Views\updateMember.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('updateMember', [], true)
 5 APPPATH\Controllers\Member.php(133): view('updateMember', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Member->updateMember('assets', 'demo', 'chart-area-demo.js')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Member))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 14:53:52 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: updateMember/assets/demo/chart-bar-demo.js]
in APPPATH\Views\updateMember.php on line 37.
 1 APPPATH\Views\updateMember.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('updateMember', [], true)
 5 APPPATH\Controllers\Member.php(133): view('updateMember', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Member->updateMember('assets', 'demo', 'chart-bar-demo.js')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Member))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 14:53:52 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: updateMember/js/datatables-simple-demo.js]
in APPPATH\Views\updateMember.php on line 37.
 1 APPPATH\Views\updateMember.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('updateMember', [], true)
 5 APPPATH\Controllers\Member.php(133): view('updateMember', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Member->updateMember('js', 'datatables-simple-demo.js')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Member))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 15:20:37 --> ErrorException: Undefined variable $announcement
[Method: GET, Route: announcement]
in APPPATH\Views\announcement.php on line 100.
 1 APPPATH\Views\announcement.php(100): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $announcement', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\announcement.php', 100)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\announcement.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('announcement', [], true)
 5 APPPATH\Controllers\Home.php(230): view('announcement', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->announcement()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 18:05:34 --> Error: Class "App\Models\PendingUserModel" not found
[Method: POST, Route: processMembership]
in APPPATH\Controllers\Pending.php on line 31.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Pending->ProcessMembership()
 2 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pending))
 3 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 7 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 18:16:39 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: updateMember/js/scripts.js]
in APPPATH\Views\updateMember.php on line 37.
 1 APPPATH\Views\updateMember.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('updateMember', [], true)
 5 APPPATH\Controllers\Member.php(133): view('updateMember', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Member->updateMember('js', 'scripts.js')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Member))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 18:16:39 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: updateMember/assets/demo/chart-area-demo.js]
in APPPATH\Views\updateMember.php on line 37.
 1 APPPATH\Views\updateMember.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('updateMember', [], true)
 5 APPPATH\Controllers\Member.php(133): view('updateMember', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Member->updateMember('assets', 'demo', 'chart-area-demo.js')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Member))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 18:16:39 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: updateMember/assets/demo/chart-bar-demo.js]
in APPPATH\Views\updateMember.php on line 37.
 1 APPPATH\Views\updateMember.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('updateMember', [], true)
 5 APPPATH\Controllers\Member.php(133): view('updateMember', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Member->updateMember('assets', 'demo', 'chart-bar-demo.js')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Member))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 18:16:39 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: updateMember/js/datatables-simple-demo.js]
in APPPATH\Views\updateMember.php on line 37.
 1 APPPATH\Views\updateMember.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('updateMember', [], true)
 5 APPPATH\Controllers\Member.php(133): view('updateMember', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Member->updateMember('js', 'datatables-simple-demo.js')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Member))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 18:17:20 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: updateMember/js/scripts.js]
in APPPATH\Views\updateMember.php on line 37.
 1 APPPATH\Views\updateMember.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('updateMember', [], true)
 5 APPPATH\Controllers\Member.php(133): view('updateMember', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Member->updateMember('js', 'scripts.js')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Member))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 18:17:20 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: updateMember/assets/demo/chart-area-demo.js]
in APPPATH\Views\updateMember.php on line 37.
 1 APPPATH\Views\updateMember.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('updateMember', [], true)
 5 APPPATH\Controllers\Member.php(133): view('updateMember', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Member->updateMember('assets', 'demo', 'chart-area-demo.js')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Member))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 18:17:20 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: updateMember/assets/demo/chart-bar-demo.js]
in APPPATH\Views\updateMember.php on line 37.
 1 APPPATH\Views\updateMember.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('updateMember', [], true)
 5 APPPATH\Controllers\Member.php(133): view('updateMember', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Member->updateMember('assets', 'demo', 'chart-bar-demo.js')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Member))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 18:17:20 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: updateMember/js/datatables-simple-demo.js]
in APPPATH\Views\updateMember.php on line 37.
 1 APPPATH\Views\updateMember.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('updateMember', [], true)
 5 APPPATH\Controllers\Member.php(133): view('updateMember', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Member->updateMember('js', 'datatables-simple-demo.js')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Member))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 18:17:39 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: updateMember/js/scripts.js]
in APPPATH\Views\updateMember.php on line 37.
 1 APPPATH\Views\updateMember.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('updateMember', [], true)
 5 APPPATH\Controllers\Member.php(133): view('updateMember', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Member->updateMember('js', 'scripts.js')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Member))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 18:17:39 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: updateMember/assets/demo/chart-area-demo.js]
in APPPATH\Views\updateMember.php on line 37.
 1 APPPATH\Views\updateMember.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('updateMember', [], true)
 5 APPPATH\Controllers\Member.php(133): view('updateMember', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Member->updateMember('assets', 'demo', 'chart-area-demo.js')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Member))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 18:17:40 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: updateMember/assets/demo/chart-bar-demo.js]
in APPPATH\Views\updateMember.php on line 37.
 1 APPPATH\Views\updateMember.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('updateMember', [], true)
 5 APPPATH\Controllers\Member.php(133): view('updateMember', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Member->updateMember('assets', 'demo', 'chart-bar-demo.js')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Member))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 18:17:40 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: updateMember/js/datatables-simple-demo.js]
in APPPATH\Views\updateMember.php on line 37.
 1 APPPATH\Views\updateMember.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php', 37)
 2 SYSTEMPATH\View\View.php(224): include('D:\\xampp\\htdocs\\Psits_System\\app\\Views\\updateMember.php')
 3 SYSTEMPATH\View\View.php(227): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1173): CodeIgniter\View\View->render('updateMember', [], true)
 5 APPPATH\Controllers\Member.php(133): view('updateMember', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Member->updateMember('js', 'datatables-simple-demo.js')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Member))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\Psits_System\\public\\index.php')
ERROR - 2025-05-24 19:50:12 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in C:\Users\Kieth\Downloads\Psits_System\system\Database\MySQLi\Connection.php:202
Stack trace:
#0 C:\Users\Kieth\Downloads\Psits_System\system\Database\MySQLi\Connection.php(202): mysqli->real_connect('localhost', 'root', '', 'psits-system', 3306, '', 0)
#1 C:\Users\Kieth\Downloads\Psits_System\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\Users\Kieth\Downloads\Psits_System\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\Users\Kieth\Downloads\Psits_System\system\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\Users\Kieth\Downloads\Psits_System\system\Model.php(676): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\Users\Kieth\Downloads\Psits_System\app\Controllers\Auth.php(14): CodeIgniter\Model->countAllResults()
#6 C:\Users\Kieth\Downloads\Psits_System\system\CodeIgniter.php(933): App\Controllers\Auth->psitsDashboard()
#7 C:\Users\Kieth\Downloads\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\Users\Kieth\Downloads\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\Users\Kieth\Downloads\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\Users\Kieth\Downloads\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\Users\Kieth\Downloads\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 C:\Users\Kieth\Downloads\Psits_System\system\rewrite.php(44): require_once('C:\\Users\\Kieth\\...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in C:\Users\Kieth\Downloads\Psits_System\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\Users\Kieth\Downloads\Psits_System\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\Users\Kieth\Downloads\Psits_System\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\Users\Kieth\Downloads\Psits_System\system\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\Users\Kieth\Downloads\Psits_System\system\Model.php(676): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#4 C:\Users\Kieth\Downloads\Psits_System\app\Controllers\Auth.php(14): CodeIgniter\Model->countAllResults()
#5 C:\Users\Kieth\Downloads\Psits_System\system\CodeIgniter.php(933): App\Controllers\Auth->psitsDashboard()
#6 C:\Users\Kieth\Downloads\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\Users\Kieth\Downloads\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Users\Kieth\Downloads\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 C:\Users\Kieth\Downloads\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\Users\Kieth\Downloads\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 C:\Users\Kieth\Downloads\Psits_System\system\rewrite.php(44): require_once('C:\\Users\\Kieth\\...')
#12 {main}
CRITICAL - 2025-05-24 19:50:12 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
[Method: GET, Route: psits-dashboard]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1733): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `pending_members`', [], false)
 3 SYSTEMPATH\Model.php(676): CodeIgniter\Database\BaseBuilder->countAllResults(true)
 4 APPPATH\Controllers\Auth.php(14): CodeIgniter\Model->countAllResults()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->psitsDashboard()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\Users\\Kieth\\Downloads\\Psits_System\\public\\index.php')
ERROR - 2025-05-24 20:05:33 --> mysqli_sql_exception: Table 'psits-system.announcements' doesn't exist in C:\Users\Kieth\Downloads\Psits_System\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\Users\Kieth\Downloads\Psits_System\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\Users\Kieth\Downloads\Psits_System\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\Users\Kieth\Downloads\Psits_System\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\Users\Kieth\Downloads\Psits_System\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\Users\Kieth\Downloads\Psits_System\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\Users\Kieth\Downloads\Psits_System\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\Users\Kieth\Downloads\Psits_System\app\Controllers\Home.php(35): CodeIgniter\BaseModel->findAll()
#7 C:\Users\Kieth\Downloads\Psits_System\system\CodeIgniter.php(933): App\Controllers\Home->announcement()
#8 C:\Users\Kieth\Downloads\Psits_System\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\Users\Kieth\Downloads\Psits_System\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\Users\Kieth\Downloads\Psits_System\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\Users\Kieth\Downloads\Psits_System\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\Users\Kieth\Downloads\Psits_System\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\Users\Kieth\Downloads\Psits_System\system\rewrite.php(44): require_once('C:\\Users\\Kieth\\...')
#14 {main}
CRITICAL - 2025-05-24 20:05:33 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'psits-system.announcements' doesn't exist
[Method: GET, Route: announcement]
in SYSTEMPATH\Database\BaseConnection.php on line 692.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `announcements`', [], false)
 2 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\Home.php(35): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->announcement()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\Users\\Kieth\\Downloads\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 20:05:33 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'psits-system.announcements' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `announcements`')
 2 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `announcements`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `announcements`', [], false)
 4 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 6 APPPATH\Controllers\Home.php(35): CodeIgniter\BaseModel->findAll()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->announcement()
 8 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('C:\\Users\\Kieth\\Downloads\\Psits_System\\public\\index.php')
CRITICAL - 2025-05-24 20:05:33 --> [Caused by] mysqli_sql_exception: Table 'psits-system.announcements' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *
FROM `announcements`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `announcements`')
 3 SYSTEMPATH\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `announcements`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `announcements`', [], false)
 5 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Controllers\Home.php(35): CodeIgniter\BaseModel->findAll()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->announcement()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\Users\\Kieth\\Downloads\\Psits_System\\public\\index.php')
